name: Envoys
main: bajan\Envoys\Main
version: 0.0.1
api: [5.0.0]
author: BajanVlogs
description: Spawn Envoys In The Warzone For You Players To Collect Items

commands:
 setenvoy:
  description: Set an envoy

  permissions:
  envoys.cmd:
    description: Allows players to use the /setenvoy command
    default: op

